### ISSUE TITLE
Peer review week 5

### ISSUE THREAD

**Issue by TatuSorjonen** [LittleHaku/ReversiAI#1]
Hello,
In total this software looks pretty good at the moment, although I'm not familiar with the game before.

Good things about user interface:
I generally like the look of the pieces. Immediately understand the situation on the board. Easy and simple. I also like how game shows who wins at the end. I really much like how closing the game asks you to confirm if you really want to close the game. I also maybe have to put this in my own work.

What I would improve in the user interface:
I would make the game window at least twice as big. I think it's a bit too small at the moment. But this is only my opinion.
I would also make separate buttons in the window for closing the game and restarting the game.

Good things about the code:
The code is clear and easy to understand
The minimax algorithm seems to work correctly. Nice job with that.

I can't say anything bad in the code. Looks fine to me.

One more thing is, I couldn't  start game with command 'make play'. It says some python version error but I think my python version 3.8 is just outdated. It would probably be good to put in the manual, which version you need to have.

**Comment by LittleHaku** [comment]
Thank you very much for the feedback :)

I didn't want to make the game very big in case it is executed on lower resolution screen like 1366x768 since although it's not the common nowadays a lot of people use older laptops for coding and someone could be using one, but I'll take it into account.

Also the Python thing I will make sure to check it out, could you please tell me if you have Poetry installed? It is my first time using it so maybe that is the problem.

Kiitos!

**Comment by TatuSorjonen** [comment]
Yeah poetry was installed and it says like this when I try to use command

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
make play
poetry run python3 src/reversi/main.py
The currently activated Python version 3.8.10 is not supported by the project (^3.10).
Trying to find and use a compatible version. 

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
make: *** [Makefile:21: play] Error 1
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

So I think my python version is just outdated and it's trying to find some new compatible version and can't find a new one.

But thats fine. I used the command 'python3 src/reversi/main.py'.

Your 'make install_poetry' command works so I don't think that's poetry's fault

**Comment by LittleHaku** [comment]
Hello Tatu, if you have time could you pull the updated repo and try to execute it now?

The `pyproject.toml` is auto generated so it got set to python 3.10 since its the version I have and now i lowered it to 3.6, also I added the restart button and a menu to choose the color

If you could tell me if it works fine now with `make play` and give me your opinion on the new reset and choose colors menu.

Thank you very much for your time :)

**Comment by TatuSorjonen** [comment]
Yeah now it's working nicely!!!

Restart button and color selection works and looks good!!!

**Comment by LittleHaku** [comment]
Thank you for your help once again, now that the things are done i'll close the issue:)

**Comment by LittleHaku** [comment]
Thank you for your help once again, now that the things are done i'll close the issue:)
